### ISSUE TITLE
TODO before workshop

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#152]
We need more granularity regarding the tools to deploy ramp.

- AWS worker:
  - [x] Merge PR https://github.com/paris-saclay-cds/ramp-board/pull/70
  - [ ] Implement error status for Worker (+ interaction with dispatcher) + teardown instance when setup was not successful
  - [x] clean-up config duplication of predictions / log folder
- Configuration:
  - [x] Finish PR https://github.com/paris-saclay-cds/ramp-board/pull/148/
  - [x] Other to do items from https://github.com/paris-saclay-cds/ramp-board/issues/121
- [x] The cloning of the repository could be done by hand and should be documented. Therefore, we can provide an option to do it automatically but it should be the main use case.
- [x] Improve the tests. We manually overwrite the config and it should be done in some other ways.
- [x] Provide template config files + a cli command to put them in the correct place
- [x] Clean-up + review of all CLI commands
- [x] Create the single `ramp` CLI entry-point (with good help message pointing to the available commands)
- [x] Update the docs
- [x] Try out full process of setting up Amazon instance for database / loop + Amazon image for launching workers 
- [x] Do not execute the notebook when deploying. Instead, just create the html. It will avoid having dependencies of all the ramp-kits which is untractable.

**Comment by jorisvandenbossche** [comment]
@glemaitre updated the to do items
