### ISSUE TITLE
TODO after workshop

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#157]
There is a couple of cleaning/nitpicks remaining:

- [ ] Creating temporary directories for deploying in tests instead of `/tmp/databoard_test`
- [ ] Removing the examples files from `ramp-utils/ramp_utils/templates` and instead use the one from the local package which should be imported from `testing.py` module
- [ ] Move some of the tools from `ramp-utils` to the ramp-*` appropriate package to limit the dependencies.

**Comment by kegl** [comment]
Once these are done we should also increment the version both in ramp-workflow and ramp-board, before we start working on new features.
