### ISSUE TITLE
Main todo list

### ISSUE THREAD

**Issue by aboucaud** [paris-saclay-cds/ramp-board#61]
Remaining todo list from #50.

**Global**
- [x] rewrite the README.md (see #54)
- [x] replace `fabric` (bad Py3 compatibility) => use of `invoke` (see #53)
- [x] global renaming 'databoard' => 'ramp-server'
- [x] add cli - need to define the scope
- [x] replace `os.system()` with `subprocess.check_call()`

**Config**
- [x] write default config file => `databoard/default_config.py`
- [x] modify the usage of config in the code - everything uses `app.config` now
- [x] remove the old config files
- [x] new variable `DATABOARD_STAGE` to be set to `PRODUCTION`, `DEVELOPMENT` or `TESTING`
 - [x] user config through the variable `DATABOARD_USER_CONFIG`: JSON or python file (easier to modify and to put comments in) ?
- [x] add a method to dump a default user config
- [x] selection of the parameters given to the users in `userconfig.json` => @mehdidc & @kegl 
- [x] `DEVELOPMENT` & `TESTING` or just `TESTING` ?
- [x] get rid of `DATABOARD_TEST` ?

**Tests**
- [x] pytest to automatically set DATABOARD_STAGE=TESTING
- [x] add more tests (see #55)
